config/routes.rb
Rails.application.routes.draw do

  resources :signed_urls
  devise_for :members

  namespace :admin do
    resources :members
    resources :signed_urls
    resources :streams, only: :index
  end

  resources :organisations
  resources :graphs do
    collection do
      get 'report'
      get 'csv'
    end
  end
  resources :statistics

  get 'signed/:short_path', to:  'pages#signed'
  get 'viewer/:short_url_key', to:  'pages#viewer'
  get 'feedback/:short_url_key', to:  'pages#feedback'
  post 'feedback/:short_url_key', to:  'pages#feedback'
  post 'survey', to:  'pages#survey'
  root to: "pages#home"
end

app/models/statistic.rb
# == Schema Information
#
# Table name: statistics
#
#  id              :bigint           not null, primary key
#  currency        :string
#  fact_column_1   :string
#  fact_column_2   :string
#  fact_column_3   :string
#  fact_column_4   :string
#  original_value  :string
#  value           :float
#  week_ending_at  :date
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  added_by_id     :bigint
#  graph_id        :bigint           not null
#  organisation_id :bigint           not null
#
# Indexes
#
#  index_statistics_on_added_by_id      (added_by_id)
#  index_statistics_on_graph_id         (graph_id)
#  index_statistics_on_organisation_id  (organisation_id)
#  index_statistics_on_week_ending_at   (week_ending_at)
#
# Foreign Keys
#
#  fk_rails_...  (graph_id => graphs.id)
#  fk_rails_...  (organisation_id => organisations.id)
#
class Statistic < ApplicationRecord
  belongs_to :organisation
  belongs_to :graph
  belongs_to :added_by, class_name: "Member"

  scope :my_recent, ->(eow, graph_id, member_id) {
    where(graph_id: graph_id).
    where(added_by_id: member_id).
    where(week_ending_at: eow)
  }

  scope :recent, ->(eow, graph_id) {
    where(graph_id: graph_id).
    where(week_ending_at: eow)
  }

  class << self
    def total_stats(eow, graph_id)
      self.recent(eow, graph_id).sum(:value)
    end

    def my_total_stats(eow, graph_id, member_id)
      self.my_recent(eow, graph_id, member_id).sum(:value)
    end
  end

  validates :value, :week_ending_at, presence: true


  def to_s
    self.graph.to_s
  end

  def value_title
    self.graph.value_title
  end

  def field_titles_array
    self.graph.field_titles_array
  end

  # def get_field_title_for(index)
  #   self.graph.get_field_title_for(index)
  # end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_statistic, only: [:show, :edit, :update, :destroy]
  before_action :set_graph, except: :autocomplete

  # GET /statistics
  # GET /statistics.json
  def index
    if current_member.member?
      @statistics = Statistic.my_recent(Time.current_eow, @graph.id, current_member.id)
    else
      @statistics = Statistic.recent(Time.current_eow, @graph.id)
    end
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    attrs = {
      graph_id: @graph.id,
      organisation_id: current_member.organisation.id,
      added_by_id: current_member.id,
      week_ending_at: Time.current_eow
    }
    @statistic = Statistic.new(attrs)
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to new_statistic_path(graph_id: @graph.id), notice: 'Statistic was successfully created.' }
        format.json { render :show, status: :created, location: @statistic }
      else
        format.html { render :new }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to statistics_path(graph_id: @graph.id), notice: 'Statistic was successfully updated.' }
        format.json { render :show, status: :ok, location: @statistic }
      else
        format.html { render :edit }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url(graph_id: @graph.id), notice: 'Statistic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graph
      g_id = if params[:statistic]
        statistic_params[:graph_id]
      elsif params[:graph_id]
        params[:graph_id]
      end
      @graph = Graph.find(g_id)
    end

    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def statistic_params
      params.require(:statistic).permit(:organisation_id, :graph_id, :added_by_id, :week_ending_at, :value, :currency, :fact_column_1, :fact_column_2, :fact_column_3, :fact_column_4)
    end
end

app/helpers/statistics_helper.rb
module StatisticsHelper

  def render_statistic(stat)
    if stat
      "#{stat}: #{stat.value}"
    else
      flash.notice || "Statistic successfully updated"
    end
  end

  def render_column_label(form, title)
    if title == "ea"
      form.input :value, label: "Enter each", input_html: { value: 1, readonly: true }
    else
      form.input :value, label: title
    end
  end

  def render_column_input(form, title, index)
    case title
    when /OTC Member/
      form.input "fact_column_#{index+1}".to_sym, label: title, as: :autocompleter, model: "Member", fieldname: "full_name", scope: "admin"
    when "Org"
      form.input "fact_column_#{index+1}".to_sym, label: title, collection: Organisation.select_list
    else
      form.input "fact_column_#{index+1}".to_sym, label: title
    end

  end

end

app/views/statistics/_flash_message.html.erb
<% flash.each do |type, msg| %>
  <div class="toast bg-<%= notice_alert_color(type) %> text-white" style="position: fixed; top: 0; right: 0;">
    <div class="toast-header">
      <strong class="mr-auto"><%= msg %></strong>
      <small>...</small>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body">
      <%= render_statistic(@statistic) %>
    </div>
  </div>
<% end %>

app/views/statistics/_form.html.erb
<%= simple_form_for(statistic) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :graph_id, as: :hidden %>
    <%= f.input :organisation_id, as: :hidden %>
    <%= f.input :added_by_id, as: :hidden %>

    <%= f.input :week_ending_at %>

    <div class="row">
      <div class="col-sm">
        <%= render_column_label(f, statistic.value_title) %>
      </div>

      <% if statistic.value_title.start_with?("Funds") %>
        <div class="col-sm">
          <%= f.input :currency, collection: ["AUD", "USD"], selected: "USD" %>
        </div>
      <% end %>

      <% statistic.field_titles_array.each_with_index do |title, index| %>
      <div class="col-sm">
        <%= render_column_input(f, title, index) %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary mb-1" %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<div class="container">

  <h1>
    Add <%= @graph %><small class="text-muted"> - <%= @graph.organisation %></small>
  </h1>

  <p><%= @graph.name %></p>
  <p><%= @graph.definition %></p>

  <%= render 'form', statistic: @statistic %>

  <%= link_to 'Show', statistic_path(@statistic, graph_id: @graph.id), class: "btn btn-primary mb-1"  %> |
  <%= link_to 'Back', statistics_path(graph_id: @graph.id), class: "btn btn-info mb-1"  %>
</div>

app/views/statistics/index.html.erb
<div class="container">
  <%= tag.h1 data: { toggle: "tooltip", placement: "top" }, title: @graph.definition do %>
    <%= @graph %><small class="text-muted"> - <%= @graph.organisation %></small>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Week ending at</th>
        <th><%= @graph.value_title || "Value" %></th>
        <% @graph.field_titles_array.each do |title| %>
          <th scope="col"><%= title %></th>
        <% end %>
        <th scope="col">Added By</th>
        <th scope="col">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @statistics.each do |statistic| %>
        <tr>
          <td><%= I18n.l(statistic.week_ending_at) %></td>
          <td><%= render_statistic_value statistic %></td>
          <% statistic.field_titles_array.each_with_index do |title, index| %>
            <td><%= statistic.send("fact_column_#{index+1}") %></td>
          <% end %>
          <td><%= statistic.added_by %></td>
          <td><%= table_action_buttons(statistic, ["graph_id", @graph.id]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= create_new_action_button("Statistic", "plus", ["graph_id", @graph.id]) %>
  <%= link_to 'Done', graphs_path, class: "btn btn-info mb-1" %>

</div>

app/views/statistics/new.html.erb
<div class="container">

  <h1>
    Add <%= @graph %><small class="text-muted"> - <%= @graph.organisation %></small>
  </h1>

  <p><%= @graph.name %></p>
  <p><%= @graph.definition %></p>

  <%= render 'form', statistic: @statistic %>

  <%= link_to 'Done', statistics_path(graph_id: @graph.id), class: "btn btn-info mb-1" %>

</div>

app/views/statistics/show.html.erb
<div class="container">
  <p>
    <strong>Organisation:</strong>
    <%= @statistic.organisation.to_s %>
  </p>

  <p>
    <strong>Graph:</strong>
    <%= @statistic.graph.to_s %>
  </p>

  <p>
    <strong>Added by:</strong>
    <%= @statistic.added_by.to_s %>
  </p>

  <p>
    <strong>Week ending at:</strong>
    <%= @statistic.week_ending_at %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= @statistic.value %>
  </p>

  <p>
    <strong>Fact column 1:</strong>
    <%= @statistic.fact_column_1 %>
  </p>

  <p>
    <strong>Fact column 2:</strong>
    <%= @statistic.fact_column_2 %>
  </p>

  <p>
    <strong>Fact column 3:</strong>
    <%= @statistic.fact_column_3 %>
  </p>

  <p>
    <strong>Fact column 4:</strong>
    <%= @statistic.fact_column_4 %>
  </p>

  <p>
    <strong>Original Value:</strong>
    <%= @statistic.original_value %>
  </p>

  <%= link_to 'Edit', edit_statistic_path(@statistic, graph_id: @graph.id), class: "btn btn-primary mb-1" %> |
  <%= link_to 'Back', statistics_path(graph_id: @graph.id), class: "btn btn-info mb-1" %>

</div>