config/routes.rb
Rails.application.routes.draw do

  resources :signed_urls
  devise_for :members

  namespace :admin do
    resources :members
    resources :signed_urls
    resources :streams, only: :index
  end

  resources :organisations
  resources :graphs do
    collection do
      get 'report'
      get 'csv'
    end
  end
  resources :statistics

  get 'signed/:short_path', to:  'pages#signed'
  get 'viewer/:short_url_key', to:  'pages#viewer'
  get 'feedback/:short_url_key', to:  'pages#feedback'
  post 'feedback/:short_url_key', to:  'pages#feedback'
  post 'survey', to:  'pages#survey'
  root to: "pages#home"
end

app/models/stream.rb
class Stream
  include ActiveModel::Model
  extend ActiveModel::Naming

  class << self
    def select_list
      load_from_file[:streams].map { |stream| [stream[:title], stream[:short_url_key]] }
    end

    def all
      streams = load_from_file[:streams].map { |stream| self.new(stream) }
    end

    def find(id)
      streams = load_from_file[:streams]
      max = streams.map { |s| s[:width] }.max
      found = streams.detect { |s| s[:short_url_key] == id }
      found.nil? ? nil : Stream.new(found.merge(max_width: max))
    end

    private

    def load_from_file
      file_path = Rails.root.join("config", "streams.yml")
      if File.exist?(file_path)
        YAML.load_file(file_path)
      end
    end
  end

  attr_accessor :title, :description, :video_id, :signed_token, :short_url_key, :width, :height, :max_width

  def ratio
    (self.height.to_f / self.width.to_f * 100)
  end

  def display_width
    (self.width.to_f / self.max_width.to_f * 100)
  end

end

app/controllers/admin/streams_controller.rb
module Admin
  class StreamsController < BaseController
    # before_action :set_stream, only: [:show, :edit, :update, :destroy]

    # GET /admin/streams
    # GET /admin/streams.json
    def index
      @streams = Stream.all
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_stream
        @stream = Stream.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def stream_params
        params.require(:stream).permit(:title, :description, :video_id, :signed_token, :short_url_key, :width, :height, :max_width)
      end
  end
end

app/views/admin/streams/_form.html.erb
<%= simple_form_for([:admin, @member]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :video_id %>
    <%= f.input :signed_token %>
    <%= f.input :short_url_key %>
    <%= f.input :width %>
    <%= f.input :height %>
    <%= f.input :max_width %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary mb-1" %>
  </div>
<% end %>

app/views/admin/streams/edit.html.erb
<div class="container">

  <h1>Editing Stream</h1>

  <%= render 'form', stream: @stream %>

  <%= link_to 'Show', admin_stream_path(@stream), class: "btn btn-primary mb-1" %>
  <%= link_to 'Back', admin_streams_path, class: "btn btn-info mb-1" %>

</div>

app/views/admin/streams/index.html.erb
<div class="container">
  <h1>Streams</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Width</th>
        <th scope="col">Height</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @streams.each do |stream| %>
        <tr>
          <td><%= stream.title %></td>
          <td><%= stream.description %></td>
          <td><%= stream.width %></td>
          <td><%= stream.height %></td>
          <td><%= link_to 'Token', new_admin_signed_url_path(short_url_key: stream.short_url_key), class: "btn btn-primary mb-1" if stream.signed_token == "TBA"  %></td>

        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/streams/new.html.erb
<div class="container">
  <h1>New Stream</h1>

  <%= render 'form', stream: @stream %>

  <%= link_to 'Back', admin_streams_path, class: "btn btn-info mb-1" %>
</div>

app/views/admin/streams/show.html.erb
<%= javascript_tag "
var key_id = '#{ENV.fetch('CLOUDFLARE_ACCOUNT_ID')}';
var video_id = '#{@stream.video_id}';
var private_key = '#{ENV.fetch('CLOUDFLARE_STREAMING_PRIVATE_KEY_PEM')}';
var expires_in = '1h';" -%>

<div class="container">
  <p>
    <strong>Title:</strong>
    <%= @stream.title.to_s %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @stream.description %>
  </p>


  <%= link_to 'Back', admin_streams_path, class: "btn btn-info mb-1" %>
</div>