config/routes.rb
Rails.application.routes.draw do

  resources :signed_urls
  devise_for :members

  namespace :admin do
    resources :members
    resources :signed_urls
    resources :streams, only: :index
  end

  resources :organisations
  resources :graphs do
    collection do
      get 'report'
      get 'csv'
    end
  end
  resources :statistics

  get 'signed/:short_path', to:  'pages#signed'
  get 'viewer/:short_url_key', to:  'pages#viewer'
  get 'feedback/:short_url_key', to:  'pages#feedback'
  post 'feedback/:short_url_key', to:  'pages#feedback'
  post 'survey', to:  'pages#survey'
  root to: "pages#home"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_member!

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || graphs_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_alert_color(type)
    case type
    when :notice
      "success"
    when :alert
      "danger"
    else
      "info"
    end
  end

  def table_action_buttons(record, vars, actions=[], commands="ed", scope=nil)
    url = "/#{record.class.name.tableize}/#{record.id}"
    url = "/#{scope}#{url}" if scope

    if commands.include?("s")
      actions << button_to(url, class: "btn btn-success btn-sm m-1", method: :get, data: { toggle: "tooltip", placement: "top" }, title: "Display this record") do
        concat tag.i(class: "bi bi-search")
        concat hidden_field_tag(vars[0].to_sym, vars[1]) unless vars.empty?
      end
    end

    if commands.include?("e")
      actions << button_to("#{url}/edit", class: "btn btn-primary btn-sm m-1", method: :get, data: { toggle: "tooltip", placement: "top" }, title: "Edit this record") do
        concat tag.i(class: "bi bi-pencil-fill")
        concat hidden_field_tag(vars[0].to_sym, vars[1]) unless vars.empty?
      end
    end

    if commands.include?("d")
      actions << button_to(url, class: "btn btn-danger btn-sm m-1", method: :delete, data: { confirm: 'Are you sure?', toggle: "tooltip", placement: "top" }, title: "Delete this record") do
        concat tag.i(class: "bi bi-trash-fill")
        concat hidden_field_tag(vars[0].to_sym, vars[1]) unless vars.empty?
      end
    end

    actions.join().html_safe
  end

  def create_new_action_button(model_name, icon_class_name="plus", vars=[])
    url = "/#{model_name.tableize}/new"

    button_to url, class: "btn btn-success mb-1", method: :get, data: { toggle: "tooltip", placement: "top" }, title: "Add a new #{model_name}" do
      concat tag.i(class: "bi bi-#{icon_class_name}") + " " + model_name
      concat hidden_field_tag(vars[0].to_sym, vars[1]) unless vars.empty?
    end
  end

  def render_statistic_value(stat)
    number_with_precision(stat.value, precision: 0) + "#{stat.currency}"
  end

end

app/views/application/_flash_message.html.erb
<% flash.each do |type, msg| %>
<div class="alert alert-<%= notice_alert_color(type) %> alert-dismissible fade show" role="alert">
  <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/application/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4 text-left">
        OT Ambassador Program
      </div>
      <div class="col-md-4 text-center">
        <%= ENV.fetch('TEST_ENVVAR_UPDATE', '-') %>
      </div>
      <div class="copyright col-md-4 text-right">
        OTC AOSH ANZO &copy; 2020 - <%= Date.today.year %>
      </div>
    </div>
  </div>
</footer>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">OTC</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
      <%= render 'navbar_maintainer_menu' %>
      <%= render 'navbar_member_menu' %>
    </ul>
  </div>
</nav>

app/views/application/_navbar_maintainer_menu.html.erb
<% if signed_in? && current_member.maintainer? %>

<li class="nav-item dropdown">
  <%= link_to "#preview", class: "nav-link", href: "javascript:;", id: "navbarDropdownMaintainer", data: { toggle: "dropdown" },  aria: { haspopup: "true", expanded: "false" } do %>
    <i class="bi bi-graph-up"></i> Stats I/C Menu
  <% end %>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMaintainer">
    <%= link_to report_graphs_path, class: "dropdown-item" do %>
      <i class="bi bi-file-earmark-break"></i> Export Compliance Report
    <% end %>
    <%= link_to csv_graphs_path, class: "dropdown-item" do %>
      <i class="bi bi-file-bar-graph-fill"></i> Export stats to csv
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to admin_members_path, class: "dropdown-item" do %>
      <i class="bi bi-person-square"></i> Members
    <% end %>
  </div>
</li>

<% end %>

app/views/application/_navbar_maintianer_menu.html.erb
<% if current_member.maintainer? %>

<li class="nav-item dropdown">
  <a class="nav-link" href="javascript:;" id="navbarDropdownMaintainer" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="bi bi-graph-up"></i>
    <span class="mr-2 d-none d-lg-inline small">Stats I/C Menu</span>
  </a>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMaintainer">
    <%= link_to "#preview", class: "dropdown-item" do %>
      <i class="bi bi-files"></i> Preview Stats
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to "#export", class: "dropdown-item" do %>
      <i class="bi bi-file-earmark-break"></i> Export to PDF
    <% end %>
    <%= link_to "#upload", class: "dropdown-item" do %>
      <i class="bi bi-file-bar-graph-fill"></i> Upload to Envisage
    <% end %>
  </div>
</li>

<% end %>

app/views/application/_navbar_member_menu.html.erb
<% if signed_in? %>

  <li class="nav-item">
    <%= link_to graphs_path, class: "nav-link" do %>
      <i class="bi bi-clipboard-data"></i>
      Add Stats
    <% end %>
  </li>

  <li class="nav-item dropdown">
    <%= link_to destroy_member_session_path, method: :delete, class: "nav-link" do %>
      <i class="bi bi-box-arrow-in-left"></i>
      Log out
      <span class="small"><%= current_member.to_s %></span>
    <% end %>
  </li>

<% else %>

  <li class="nav-item">
    <%= link_to new_member_session_path, class: "nav-link" do %>
      <i class="bi bi-box-arrow-in-right"></i> Log in
    <% end %>
  </li>

<% end %>