config/routes.rb
Rails.application.routes.draw do

  resources :signed_urls
  devise_for :members

  namespace :admin do
    resources :members
    resources :signed_urls
    resources :streams, only: :index
  end

  resources :organisations
  resources :graphs do
    collection do
      get 'report'
      get 'csv'
    end
  end
  resources :statistics

  get 'signed/:short_path', to:  'pages#signed'
  get 'viewer/:short_url_key', to:  'pages#viewer'
  get 'feedback/:short_url_key', to:  'pages#feedback'
  post 'feedback/:short_url_key', to:  'pages#feedback'
  post 'survey', to:  'pages#survey'
  root to: "pages#home"
end

app/models/signed_url.rb
# == Schema Information
#
# Table name: signed_urls
#
#  id         :bigint           not null, primary key
#  email      :string
#  expires_in :integer
#  short_path :string
#  token      :string
#  used_at    :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  stream_id  :string
#
class SignedUrl < ApplicationRecord
  def check_valid_details(user_name, password)
    (user_name == email || password == email)
  end
end

app/controllers/admin/signed_urls_controller.rb
module Admin
  class SignedUrlsController < BaseController
    before_action :set_signed_url, only: [:show, :edit, :update, :destroy]

    # GET /signed_urls
    # GET /signed_urls.json
    def index
      @signed_urls = SignedUrl.all
    end

    # GET /signed_urls/1
    # GET /signed_urls/1.json
    def show
    end

    # GET /signed_urls/new
    def new
      @stream = Stream.find(params[:short_url_key])
      redirect_to streams_path, alert: "Must pass the Stream to the NEW action" if @stream.nil?

      attribs = {
        stream_id: @stream.short_url_key,
        short_path: SecureRandom.hex(10),
        expires_in: ENV.fetch('SIGNING_EXPIRES_IN').to_i,
      }
      @signed_url = SignedUrl.new(attribs)
    end

    # GET /signed_urls/1/edit
    def edit
      @stream = Stream.find(@signed_url.stream_id)
    end

    # POST /signed_urls
    # POST /signed_urls.json
    def create
      @signed_url = SignedUrl.new(signed_url_params)

      respond_to do |format|
        if @signed_url.save
          format.html { redirect_to admin_signed_url_path(@signed_url), notice: 'Signed url was successfully created.' }
          format.json { render :show, status: :created, location: @signed_url }
        else
          format.html { render :new }
          format.json { render json: @signed_url.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /signed_urls/1
    # PATCH/PUT /signed_urls/1.json
    def update
      respond_to do |format|
        if @signed_url.update(signed_url_params)
          format.html { redirect_to admin_signed_url_path(@signed_url), notice: 'Signed url was successfully updated.' }
          format.json { render :show, status: :ok, location: @signed_url }
        else
          format.html { render :edit }
          format.json { render json: @signed_url.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /signed_urls/1
    # DELETE /signed_urls/1.json
    def destroy
      @signed_url.destroy
      respond_to do |format|
        format.html { redirect_to admin_signed_urls_url, notice: 'Signed url was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_signed_url
        @signed_url = SignedUrl.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def signed_url_params
        params.require(:signed_url).permit(:email, :token, :stream_id, :expires_in, :short_path, :used_at, :generated_at)
      end
  end
end

app/views/admin/signed_urls/_form.html.erb
<%= javascript_tag "
var key_id = '#{ENV.fetch('CLOUDFLARE_ACCOUNT_ID')}';
var video_id = '#{@stream.video_id}';
var private_key = '#{ENV.fetch('CLOUDFLARE_STREAMING_PRIVATE_KEY_PEM')}';
var expires_in = '3h';" -%>

<%= simple_form_for([:admin, @signed_url]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :email, as: :email, required: true %>
    <%= f.input :expires_in, hint: "seconds" %>
    <%= f.input :stream_id, collection: Stream.select_list, readonly: :readonly %>
    <%= f.input :token, readonly: true %>
    <%= f.input :short_path, readonly: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary mb-1" %>
  </div>
<% end %>

app/views/admin/signed_urls/edit.html.erb
<div class="container">
  <h1>Editing Signed Url</h1>

  <%= render 'form', signed_url: @signed_url %>

  <%= link_to 'Show', @signed_url, class: "btn btn-primary mb-1" %> |
  <%= link_to 'Back', admin_signed_urls_path, class: "btn btn-info mb-1" %>
</div>

app/views/admin/signed_urls/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <h1>Signed Urls</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Email</th>
        <th>Stream</th>
        <th>Created at</th>
        <th>Expires at</th>
        <th>Used at</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @signed_urls.each do |signed_url| %>
        <tr>
          <td><%= signed_url.email %></td>
          <td><%= signed_url.stream_id %></td>
          <td><%= I18n.l(signed_url.created_at, format: :short) %></td>
          <td><%= I18n.l(signed_url.created_at + signed_url.expires_in, format: :short) %></td>
          <td><%= I18n.l(signed_url.used_at, format: :short) if signed_url.used_at %></td>
          <td><%= link_to 'Show', admin_signed_url_path(signed_url), class: "btn btn-secondary mb-1" %></td>
          <td><%= link_to 'Edit', edit_admin_signed_url_path(signed_url), class: "btn btn-primary mb-1" %></td>
          <td><%= link_to 'Destroy', admin_signed_url_path(signed_url), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mb-1" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Signed Url', admin_streams_path, class: "btn btn-primary mb-1" %>
</div>

app/views/admin/signed_urls/new.html.erb
<div class="container">

  <h1>New Signed Url</h1>

  <%= render 'form', signed_url: @signed_url %>

  <%= link_to 'Back', admin_signed_urls_path, class: "btn btn-info mb-1" %>

</div>

app/views/admin/signed_urls/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Email:</strong>
    <%= @signed_url.email %>
  </p>

  <p>
    <strong>Token:</strong>
    [FILTERED]
  </p>

  <p>
    <strong>Stream:</strong>
    <%= @signed_url.stream_id %>
  </p>

  <p>
    <strong>Expires in:</strong>
    <%= @signed_url.expires_in %>secs
  </p>

  <p>
    <strong>Link:</strong>
    <%= File.join(ENV.fetch('HOST_URL'), 'signed', @signed_url.short_path) %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= @signed_url.created_at %>
  </p>

  <p>
    <strong>Used at:</strong>
    <%= @signed_url.used_at %>
  </p>

  <%= link_to 'Edit', edit_admin_signed_url_path(@signed_url), class: "btn btn-primary mb-1" %> |
  <%= link_to 'Back', admin_signed_urls_path, class: "btn btn-info mb-1" %>

</div>